BSDPy: 
  image: bruienne/bsdpy
  environment: 
    BSDPY_IP: 192.168.254.22
  ports:
    - "69:69/udp"
    - "67:67/udp"
    - "80:80"
  volumes:
    - /srv/bsdpy/nbi:/nbi:rw
Samba:
  image: dperson/samba
  command: [samba.sh, 
    -u nbi;nbi,
    -s images;/nbi;yes;no,
    -w MSDOM] 
  ports:
    - "138:138/udp"
    - "139:139/udp"
    - "445:445/udp"
    - "445:445"
  volumes:
    - /srv/bsdpy/nbi:/nbi:rw


